vim.keymap.set('n', '<C-h>', '<cmd>wincmd h<CR>')
vim.keymap.set('n', '<C-j>', '<cmd>wincmd j<CR>')
vim.keymap.set('n', '<C-k>', '<cmd>wincmd k<CR>')
vim.keymap.set('n', '<C-l>', '<cmd>wincmd l<CR>')
vim.keymap.set('n', '<Up>', '<cmd>wincmd -<CR>')
vim.keymap.set('n', '<Down>', '<cmd>wincmd +<CR>')
vim.keymap.set('n', '<Left>', '<cmd>wincmd <<CR>')
vim.keymap.set('n', '<Right>', '<cmd>wincmd ><CR>')
vim.keymap.set('n', '<Leader>h', ':nohlsearch<CR>')
vim.keymap.set('n', '<Leader>l', ':set invrelativenumber<CR>')
-- vim.keymap.set('n', '<S-j>', '<cmd>m +1<CR>')
-- vim.keymap.set('n', '<S-k>', '<cmd>m -2<CR>')
